[package]
name = "raphael-model-manager"
version = "0.1.0"
description = "Raphael Model Manager"
authors = ["Prathik TS"]
edition = "2021"

[lib]
name = "raphael_model_manager_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.1" }

[dependencies]
tauri = { version = "2.11.1", features = ["tray-icon", "devtools", "protocol-asset"] }
tauri-plugin-dialog = "2.7.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
walkdir = "2.5"
notify = "8.2"
sha2 = "0.10"
hex = "0.4"
reqwest = { version = "0.12", default-features = false, features = ["json", "stream", "rustls-tls"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "time"] }
futures-util = "0.3"
url = "2.5"
chrono = { version = "0.4", features = ["serde"] }
image = { version = "0.25", default-features = false, features = ["jpeg", "png", "webp"] }
keyring = { version = "3.6", features = ["windows-native"] }
thiserror = "2"
urlencoding = "2.1"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
strip = true
opt-level = "s"
